Edziennik/Areas/Shared/Controllers/HomeController.cs
using Edziennik.Data;
using Edziennik.Data.Models;
using Edziennik.Models;
using Edziennik.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Edziennik.Controllers
{
    [Area("Shared")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext dbContext;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext dbContext)
        {
            _logger = logger;
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Message(int id)
        {
            var  message = dbContext.Messages.Include(x=>x.Author).FirstOrDefault(x => x.Id == id);
            message.Opened = true;
            dbContext.SaveChanges();
            return View(message);
        }
        public IActionResult Messages()
        {
            var claim = SharedFunctions.getClaim(User);
            var messages = dbContext.Messages.Include(x=>x.Author).Where(x=>x.ReciverId==claim.Value);
            return View(messages);
        }
        public IActionResult CreateMessage()
        {
            var claim = SharedFunctions.getClaim(User);
            var user = dbContext.ApplicationUsers.FirstOrDefault(x => x.Id == claim.Value);
            var message = new Message() { Author = user, AuthorId = claim.Value };
            var users = dbContext.ApplicationUsers.ToList();
            users.Remove(user);
            ViewBag.Users = users;
            return View(message);
        }
        [HttpPost]
        public IActionResult CreateMessage(Message message)
        {
            if (ModelState.IsValid)
            {
                dbContext.Messages.Add(message);
                dbContext.SaveChanges();
                return RedirectToAction("Messages");
            }
            var claim = SharedFunctions.getClaim(User);
            var user = dbContext.ApplicationUsers.FirstOrDefault(x => x.Id == claim.Value);
            var users = dbContext.ApplicationUsers.ToList();
            users.Remove(user);
            ViewBag.Users = users;
            return View(message);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Edziennik/ViewComponents/MessagesViewComponent.cs
using Edziennik.Data;
using Edziennik.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Edziennik.ViewComponents
{
    public class MessagesViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext dbContext;

        public MessagesViewComponent(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claim = SharedFunctions.getClaim((ClaimsPrincipal)User);
            if(claim != null)
            {
                var messages = dbContext.Messages.Where(u=>u.ReciverId==claim.Value).Where(x=>x.Opened==false).ToList();
                HttpContext.Session.SetInt32(SD.Messages, messages.Count);
                return View(HttpContext.Session.GetInt32(SD.Messages));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

Edziennik/Views/Shared/_Layout.cshtml
@using Edziennik.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Edziennik</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Edziennik.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Edziennik</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.Role_Student))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Student" asp-controller="Home" asp-action="Plan">Student's Plan</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Student))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Student" asp-controller="Home" asp-action="Grades">Grades</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Teacher))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Teacher" asp-controller="Home" asp-action="Plan">Teacher's Plan</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Teacher))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Teacher" asp-controller="Home" asp-action="Students">Students</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Teacher) || User.IsInRole(SD.Role_Student))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Messages">@await Component.InvokeAsync("Messages")</a>
                        </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin)){
                        <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Managing</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="AddStudent">Add Student</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="AddTeacher">Add Teacher</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="AddClass">Add Class</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="AddLesson">Add Lesson</a>
                                </div>
                            </li>
                        }
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>